/**
 * Provides interfaces and concrete implementations for defining {@code Products} (see
 * {@link au.gov.aims.ereefs.pojo.definition.product.ProductDefinition}) generated by the system.
 * A specialised {@code Dao} interface (see
 * {@link au.gov.aims.ereefs.pojo.definition.product.ProductDefinition}) provides abstract
 * access for interacting with the records in the repository, along with both a file-based
 * implementation
 * ({@link au.gov.aims.ereefs.pojo.definition.product.ProductDefinitionDaoFileImpl}) and a
 * {@code MongoDB}-based implementation
 * ({@link au.gov.aims.ereefs.pojo.definition.product.ProductDefinitionDaoMongoDbImpl}).
 */
package au.gov.aims.ereefs.pojo.definition.product;