package au.gov.aims.ereefs.pojo;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * Base class for POJOs (Plain Old Java Objects) that represent a single object/record in the
 * system.
 *
 * @author Aaron Smith
 */
public class Pojo {

    /**
     * Unique identifier for the {@code Pojo}.
     */
    @JsonProperty("_id")
    protected String id;

    public String getId() {
        return this.id;
    }

    /**
     * Constructor to capture the parameter(s).
     *
     * @param id the unique identifier to use for this {@code Pojo}. If {@code null}, a unique
     *           {@code id} will be generated by concatenating the object type
     *           ({@code this.getClass().getSimpleName()} with a {@code UUID}.
     */
    public Pojo(String id) {
        super();

        if (id != null) {
            this.id = id;
        } else {
            String type = this.getClass().getSimpleName();
            this.id = type + "_" + UUID.randomUUID().toString();
        }

    }

}
