# Workflow executed on "release" events.
name: release

on:
  release:
    types: [published]

jobs:

  # Deploy to Github Packages.
  deploy:
    name: Deploy to Github Packages

    runs-on: ubuntu-latest

    # Start MongoDB in a Docker container for testing.
    services:
      mongodb:
        image: mongo:4.4.0
        ports:
          - 27017

    # Run the tests in a Maven Docker container.
    container:
      image: maven:3.6-alpine
      env:
        MONGODB_URL: 'mongodb://mongodb:27017'

    steps:

      # Retrieve the code from Github.
      - uses: actions/checkout@v2

      - name: Publish to GitHub Packages.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -e --settings maven-settings.xml clean test deploy

